<?php

class Countries
{
    /** @return array<string,string> ISO-3166-1 alpha-2 => name */
    public static function all(): array
    {
        return [
            'AF' => 'Afeganistão', 'ZA' => 'África do Sul', 'AL' => 'Albânia',
            'DE' => 'Alemanha', 'AD' => 'Andorra', 'AO' => 'Angola',
            'AI' => 'Anguilla', 'AQ' => 'Antártida', 'AG' => 'Antígua e Barbuda',
            'SA' => 'Arábia Saudita', 'DZ' => 'Argélia', 'AR' => 'Argentina',
            'AM' => 'Armênia', 'AW' => 'Aruba', 'AU' => 'Austrália',
            'AT' => 'Áustria', 'AZ' => 'Azerbaijão', 'BS' => 'Bahamas',
            'BH' => 'Bahrein', 'BD' => 'Bangladesh', 'BB' => 'Barbados',
            'BE' => 'Bélgica', 'BZ' => 'Belize', 'BJ' => 'Benin',
            'BM' => 'Bermudas', 'BY' => 'Bielorrússia', 'BO' => 'Bolívia',
            'BA' => 'Bósnia e Herzegovina', 'BW' => 'Botsuana', 'BR' => 'Brasil',
            'BN' => 'Brunei', 'BG' => 'Bulgária', 'BF' => 'Burkina Faso',
            'BI' => 'Burundi', 'BT' => 'Butão', 'CV' => 'Cabo Verde',
            'CM' => 'Camarões', 'KH' => 'Camboja', 'CA' => 'Canadá',
            'QA' => 'Catar', 'KZ' => 'Cazaquistão', 'TD' => 'Chade',
            'CL' => 'Chile', 'CN' => 'China', 'CY' => 'Chipre',
            'CO' => 'Colômbia', 'KM' => 'Comores', 'CG' => 'Congo',
            'CD' => 'Congo (RDC)', 'KP' => 'Coreia do Norte', 'KR' => 'Coreia do Sul',
            'CI' => 'Costa do Marfim', 'CR' => 'Costa Rica', 'HR' => 'Croácia',
            'CU' => 'Cuba', 'CW' => 'Curaçao', 'DK' => 'Dinamarca',
            'DJ' => 'Djibuti', 'DM' => 'Dominica', 'EG' => 'Egito',
            'SV' => 'El Salvador', 'AE' => 'Emirados Árabes Unidos', 'EC' => 'Equador',
            'ER' => 'Eritreia', 'SK' => 'Eslováquia', 'SI' => 'Eslovênia',
            'ES' => 'Espanha', 'US' => 'Estados Unidos', 'EE' => 'Estônia',
            'ET' => 'Etiópia', 'FJ' => 'Fiji', 'PH' => 'Filipinas',
            'FI' => 'Finlândia', 'FR' => 'França', 'GA' => 'Gabão',
            'GM' => 'Gâmbia', 'GH' => 'Gana', 'GE' => 'Geórgia',
            'GS' => 'Geórgia do Sul', 'GI' => 'Gibraltar', 'GD' => 'Granada',
            'GR' => 'Grécia', 'GL' => 'Groenlândia', 'GP' => 'Guadalupe',
            'GU' => 'Guam', 'GT' => 'Guatemala', 'GG' => 'Guernsey',
            'GY' => 'Guiana', 'GF' => 'Guiana Francesa', 'GN' => 'Guiné',
            'GQ' => 'Guiné Equatorial', 'GW' => 'Guiné-Bissau', 'HT' => 'Haiti',
            'NL' => 'Holanda (Países Baixos)', 'HN' => 'Honduras', 'HK' => 'Hong Kong',
            'HU' => 'Hungria', 'YE' => 'Iêmen', 'BV' => 'Ilha Bouvet',
            'CX' => 'Ilha Christmas', 'IM' => 'Ilha de Man', 'NF' => 'Ilha Norfolk',
            'AX' => 'Ilhas Aland', 'KY' => 'Ilhas Cayman', 'CC' => 'Ilhas Cocos',
            'CK' => 'Ilhas Cook', 'FO' => 'Ilhas Faroe', 'FK' => 'Ilhas Falkland',
            'MP' => 'Ilhas Marianas do Norte', 'MH' => 'Ilhas Marshall', 'PN' => 'Ilhas Pitcairn',
            'SB' => 'Ilhas Salomão', 'TC' => 'Ilhas Turks e Caicos', 'VG' => 'Ilhas Virgens Britânicas',
            'VI' => 'Ilhas Virgens Americanas', 'IN' => 'Índia', 'ID' => 'Indonésia',
            'IR' => 'Irã', 'IQ' => 'Iraque', 'IE' => 'Irlanda',
            'IS' => 'Islândia', 'IL' => 'Israel', 'IT' => 'Itália',
            'JM' => 'Jamaica', 'JP' => 'Japão', 'JE' => 'Jersey',
            'JO' => 'Jordânia', 'KW' => 'Kuwait', 'LA' => 'Laos',
            'LS' => 'Lesoto', 'LV' => 'Letônia', 'LB' => 'Líbano',
            'LR' => 'Libéria', 'LY' => 'Líbia', 'LI' => 'Liechtenstein',
            'LT' => 'Lituânia', 'LU' => 'Luxemburgo', 'MO' => 'Macau',
            'MK' => 'Macedônia do Norte', 'MG' => 'Madagascar', 'MY' => 'Malásia',
            'MW' => 'Malawi', 'MV' => 'Maldivas', 'ML' => 'Mali',
            'MT' => 'Malta', 'MA' => 'Marrocos', 'MQ' => 'Martinica',
            'MU' => 'Maurício', 'MR' => 'Mauritânia', 'YT' => 'Mayotte',
            'MX' => 'México', 'FM' => 'Micronésia', 'MZ' => 'Moçambique',
            'MD' => 'Moldávia', 'MC' => 'Mônaco', 'MN' => 'Mongólia',
            'ME' => 'Montenegro', 'MS' => 'Montserrat', 'MM' => 'Mianmar',
            'NA' => 'Namíbia', 'NR' => 'Nauru', 'NP' => 'Nepal',
            'NI' => 'Nicarágua', 'NE' => 'Níger', 'NG' => 'Nigéria',
            'NU' => 'Niue', 'NO' => 'Noruega', 'NC' => 'Nova Caledônia',
            'NZ' => 'Nova Zelândia', 'OM' => 'Omã', 'PW' => 'Palau',
            'PS' => 'Palestina', 'PA' => 'Panamá', 'PG' => 'Papua Nova Guiné',
            'PK' => 'Paquistão', 'PY' => 'Paraguai', 'PE' => 'Peru',
            'PF' => 'Polinésia Francesa', 'PL' => 'Polônia', 'PR' => 'Porto Rico',
            'PT' => 'Portugal', 'KE' => 'Quênia', 'KG' => 'Quirguistão',
            'KI' => 'Kiribati', 'GB' => 'Reino Unido', 'CF' => 'República Centro-Africana',
            'DO' => 'República Dominicana', 'CZ' => 'República Tcheca', 'RE' => 'Reunião',
            'RO' => 'Romênia', 'RW' => 'Ruanda', 'RU' => 'Rússia',
            'EH' => 'Saara Ocidental', 'PM' => 'Saint Pierre e Miquelon', 'AS' => 'Samoa Americana',
            'WS' => 'Samoa', 'SM' => 'San Marino', 'SH' => 'Santa Helena',
            'LC' => 'Santa Lúcia', 'BL' => 'São Bartolomeu', 'KN' => 'São Cristóvão e Nevis',
            'MF' => 'São Martinho (FR)', 'SX' => 'São Martinho (NL)', 'ST' => 'São Tomé e Príncipe',
            'VC' => 'São Vicente e Granadinas', 'SN' => 'Senegal', 'SL' => 'Serra Leoa',
            'RS' => 'Sérvia', 'SC' => 'Seicheles', 'SG' => 'Singapura',
            'SY' => 'Síria', 'SO' => 'Somália', 'LK' => 'Sri Lanka',
            'SZ' => 'Essuatíni', 'SD' => 'Sudão', 'SS' => 'Sudão do Sul',
            'SE' => 'Suécia', 'CH' => 'Suíça', 'SR' => 'Suriname',
            'TJ' => 'Tajiquistão', 'TH' => 'Tailândia', 'TW' => 'Taiwan',
            'TZ' => 'Tanzânia', 'TL' => 'Timor-Leste', 'TG' => 'Togo',
            'TK' => 'Tokelau', 'TO' => 'Tonga', 'TT' => 'Trinidad e Tobago',
            'TN' => 'Tunísia', 'TM' => 'Turcomenistão', 'TR' => 'Turquia',
            'TV' => 'Tuvalu', 'UA' => 'Ucrânia', 'UG' => 'Uganda',
            'UY' => 'Uruguai', 'UZ' => 'Uzbequistão', 'VU' => 'Vanuatu',
            'VA' => 'Vaticano', 'VE' => 'Venezuela', 'VN' => 'Vietnã',
            'WF' => 'Wallis e Futuna', 'ZM' => 'Zâmbia', 'ZW' => 'Zimbábue',
        ];
    }

    public static function isValidCode(string $code): bool
    {
        return isset(self::all()[strtoupper($code)]);
    }
}
